- README.md:
  - description: No TODO markers left in README.md
    category: Documentation
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- README.md:
  - description: We need better headings
    category: Documentation
    check: CountMarkdownTags
    options:
      tag: heading
      count: 2
      exact: false

- README.md:
  - description: Have at least 3 TODOs
    category: Documentation
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 3
      exact: false

# Am I really that commited?

- description: Make at least one commit, you moron
  category: git
  check: CountCommits
  badges:
    - name: "Committed"
      step: 1
    - name: "Overly committed"
      step: 1
  options:
    count: 1
- description: Make at least 10 commits, you moron
  category: git
  check: CountCommits
  badges:
    - name: "Overly committed"
      step: 2
  options:
    count: 10
- description: Make at least 15 commits, you moron
  category: git
  check: CountCommits
  badges:
    - name: "Overly committed"
      step: 3
  options:
    count: 15
